force-app/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Load Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Load__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <summarizedField>LoadProduct__c.Value__c</summarizedField>
    <summaryForeignKey>LoadProduct__c.Load__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Load__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LoadProduct__c/LoadProduct__c.object-meta.xml
<CustomObject>
    <label>Load Product</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Load Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Load Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadProduct__c/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <label>Load</label>
    <referenceTo>Load__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Load_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LoadProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>EventProduct__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>LoadProducts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LoadProduct__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <formula>UnitPrice__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationProduct__c/LocationProduct__c.object-meta.xml
<CustomObject>
    <label>Location Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationProduct__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>LocationProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>EventProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewLoadController.cls
public with sharing class NewLoadController {
    @AuraEnabled(cacheable=true)
    public static List<LoadProduct> getProducts(Id locationId){
        List<LoadProduct> loadProducts = new List<LoadProduct>();
        for(LocationProduct__c locationProduct : [SELECT Id, Name, UnitPrice__c FROM LocationProduct__c WHERE Location__c = :locationId ORDER BY UnitPrice__c]){
            LoadProduct loadProduct = new LoadProduct(
                locationProduct.Id,
                locationProduct.Name,
                locationProduct.UnitPrice__c,
                0
            );
            loadProducts.add(loadProduct);
        }
        return loadProducts;
    }

    @AuraEnabled
    public static void createLoadProduct(string productsFromLwc, Id vendorId){
        Load__c load = new Load__c(Vendor__c = vendorId);
        insert load;

        List<LoadProduct__c> loadProducts = new List<LoadProduct__c>();
        for(LoadProduct productFromLWC : (List<LoadProduct>)JSON.deserialize(productsFromLWC, List<LoadProduct>.class)){
            LoadProduct__c loadProduct = new LoadProduct__c(
                Load__c = load.Id,
                Product__c = productFromLWC.productId,
                Quantity__c = productFromLWC.quantity
            );
            loadProducts.add(loadProduct);
        }
        insert loadProducts;
    }

    @AuraEnabled(cacheable=true)
    public static List<Load__c> getLoads(Id vendorId){
        return [SELECT Id, Name, CreatedDate, Value__c FROM Load__c WHERE Vendor__c = :vendorId ORDER BY CreatedDate DESC];
    }

    public class LoadProduct{
        @AuraEnabled
        public Id productId;

        @AuraEnabled
        public String name;

        @AuraEnabled
        public Decimal unitPrice;

        @AuraEnabled
        public Integer quantity;

        public LoadProduct(){}

        public LoadProduct(Id productId, String name, Decimal unitPrice, Integer quantity){
            this.productId = productId;
            this.name = name;
            this.unitPrice = unitPrice;
            this.quantity = quantity;
        }
    }

}